#!/bin/bash
#PBS -l walltime=00:01:00
#PBS -l nodes=1:ppn=1
#PBS -N qsub_sp_result
#PBS -j oe
cd $PBS_O_WORKDIR
./sparsecoding_test < testcase1.txt > out1.txt
echo "test 1 done"
./sparsecoding_test < testcase2.txt > out2.txt
echo "test 2 done."
./sparsecoding_test < testcase3.txt > out3.txt
echo "test 3 done."
./sparsecoding_test < testcase4.txt > out4.txt
echo "test 4 done."
echo "64 16" | ./sparsemult_test > outmult.txt
