#!/bin/bash
#PBS -l walltime=00:01:00
#PBS -l nodes=1:ppn=1
#PBS -N qsub_sp_result
#PBS -j oe
cd $PBS_O_WORKDIR
./sparsecoding_test < testcase1.txt > out1.txt
echo "job 1 done"
./sparsecoding_test < testcase2.txt > out2.txt
echo "job 2 done."
./sparsecoding_test < testcase3.txt > out3.txt
echo "job 3 done."
./sparsecoding_test < testcase4.txt > out4.txt
echo "job 4 done."
./sparsecoding_test < testcase5.txt > out5.txt
echo "job 4 done."
